### PR TITLE
Implement get_client_variable_as_string

### PR DESCRIPTION
**Pull request by 0xpr03**
Signed-off-by: Aron Heinecke <aron.heinecke@t-online.de>

### CODE REVIEW

**Comment by Flakebi** [comment]
Hm, there exists already the function [`Connection::get_client_property_as_string`](https://github.com/ReSpeak/rust-ts3plugin/blob/master/src/lib.rs#L535).
I think you could just make that one public if you need a wrapper for `get_client_variable_as_string`.

Apart from that, all client variables should be available as high-level functions on the connection struct: [Here is a list](https://docs.rs/ts3plugin/0.2.1/ts3plugin/struct.Connection.html).

Is there some property missing? Or do you need this function for something else?

**Comment by 0xpr03** [comment]
Ah yeah that would also be possible.
I wanted to leave it to the caller if he needs a (lossy) owned version or just a &str.
I personally just need the private method.

I'm missing any free_mem function call in your implementation ? This is documented as required by the docs.

**Comment by Flakebi** [comment]
Hmm, you are right, there is a free missing somewhere…

**Comment by Flakebi** [comment]
Thanks for the notice, strings are freed now on the master branch.
I also added 2 functions to get the `TsApi` and the `Plugin` statically.
(And Connection::get_client_property_as_string is now public.)

**Comment by 0xpr03** [comment]
Thanks for adding this.

**Comment by 0xpr03** [comment]
Why did you make `get_client_property_as_string` hidden in the docs ?

I'm trying to access the server groups currently, which is marked as WIP.

**Comment by 0xpr03** [comment]
Edit: Resolved

My approach didn't require the owning of server id and invoker ID but it works.

**Comment by Flakebi** [comment]
I hid the function in the docs because this is not the intended api to get client properties. In the best case, all properties would be available on the client struct.

The server and connection id are both an u64, so copying them is no loss, a reference has the same size.

**Pull request closed without merging**
